Vagrant.configure("2") do |config|

    # Master Nodes
    MasterCount = 1
    (1..MasterCount).each do |i|
        config.vm.define "k8s-master-#{i}" do |master|
            master.vm.box = "gutehall/ubuntu24-10"
            master.vm.box_version = "2024.10.11"
            master.vm.hostname = "k8s-master-#{i}"
            master.vm.network "private_network", ip: "172.16.10.1#{i}"

            master.vm.provider :vmware_workstation do |vb|
                vb.gui = true
				vb.memory = 4096
				vb.cpus = 2
				vb.vmx["displayname"] = "k8s-master-#{i}"
            end
        end
    end

    # Worker Nodes
    WorkerCount = 3
    (1..WorkerCount).each do |i|
        config.vm.define "k8s-worker-#{i}" do |worker|
            worker.vm.box = "gutehall/ubuntu24-10"
            worker.vm.box_version = "2024.10.11"
            worker.vm.hostname = "k8s-worker-#{i}"
            worker.vm.network "private_network", ip: "172.16.16.1#{i}"

            worker.vm.provider :vmware_workstation do |vb|
                vb.gui = true
				vb.memory = 4096
				vb.cpus = 2
				vb.vmx["displayname"] = "k8s-worker-#{i}"
            end
        end
    end

    config.vm.provision "shell" do |s|
        s.inline = <<-SHELL
            echo 'vagrant ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
        SHELL
    end

end
